/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'salonState': MotiaStream<{ revenue: number; appointments: number; inventory: { gel: number; cream: number; dye: number; mask: number }; lastActivity?: { text: string; time: string } }>
  }

  interface Handlers {
    'InitSalon': ApiRouteHandler<{ inventory: { gel: number; cream: number; dye: number; mask: number } }, ApiResponse<200, { success: boolean; message: string }> | ApiResponse<400, { error: string }>, never>
    'BookService': ApiRouteHandler<{ serviceKey: 'haircut' | 'shave' | 'color' | 'spa'; customerName: string }, ApiResponse<200, { success: boolean; message: string }> | ApiResponse<400, { error: string }>, never>
  }
    
}